module Model

open Magic
open Domain

type Propulsion =
    | Flight
    | Hover
    | Wheel
    | Legs
    | Treads

type Utility =
    | Device
    | Processor
    | Armor
    | Storage

type Weapon =
    | Launcher
    | Gun
    | Cannon
    | Special
    | Melee

type ItemCategory =
    | Power
    | Propulsion of Propulsion
    | Utility of Utility
    | Weapon of Weapon
    | Misc
    | Matter

let itemToCategory (item: Item) : ItemCategory =
    match item with
    | Item.Matter -> Matter
    | Item.DataCore
    | Item.DerelictLog
    | Item.SchematicArchive
    | Item.ImprinterDataCore
    | Item.A2DataCore
    | Item.A7DataCore
    | Item.MaincDataCore
    | Item.ArchitectDataCore
    | Item.Scrap
    | Item.Protomatter -> Misc
    | Item.IonEngine
    | Item.LgtIonEngine
    | Item.BackupPowerI
    | Item.ImpIonEngine
    | Item.RnfIonEngine
    | Item.HvyIonEngine
    | Item.CldIonEngine
    | Item.DeuteriumEngine
    | Item.LgtDeuteriumEngine
    | Item.BackupPowerIii
    | Item.NuclearCore
    | Item.LgtNuclearCore
    | Item.ImpDeuteriumEngine
    | Item.RnfDeuteriumEngine
    | Item.HybDeuteriumEngine
    | Item.HvyDeuteriumEngine
    | Item.CldDeuteriumEngine
    | Item.EnhNuclearCore
    | Item.MicNuclearCore
    | Item.MakPowerSource
    | Item.AngularMomentumEngine
    | Item.LgtAngularMomentumEngine
    | Item.FcellEngine
    | Item.FissionCore
    | Item.LgtFissionCore
    | Item.HybFissionCore
    | Item.FusionCompressor
    | Item.ColdFusionReactor
    | Item.NeutrinoCore
    | Item.LgtNeutrinoCore
    | Item.RnfFissionCore
    | Item.EnhFissionCore
    | Item.CldFissionCore
    | Item.MicFissionCore
    | Item.FusionReactor
    | Item.AntimatterReactor
    | Item.LgtAntimatterReactor
    | Item.RnfAntimatterReactor
    | Item.HybAntimatterReactor
    | Item.BackupPowerVii
    | Item.HvyAntimatterReactor
    | Item.MniFusionReactor
    | Item.ImpFusionCompressor
    | Item.MicNeutrinoCore
    | Item.ZioLightDmReactor
    | Item.ZioHeavyDmReactor
    | Item.ParticleReactor
    | Item.LgtParticleReactor
    | Item.MicAntimatterReactor
    | Item.ComParticleReactor
    | Item.CldAntimatterReactor
    | Item.GravitonReactor
    | Item.AsbFluxGenerator
    | Item.QuantumReactor
    | Item.LgtQuantumReactor
    | Item.RnfQuantumReactor
    | Item.ImpQuantumReactor
    | Item.ZeropointReactor
    | Item.VortexChainReactor
    | Item.SingularityReactor -> Power
    | Item.MatterDrive -> Utility Device
    | Item.LgtTreads
    | Item.ImpTreads
    | Item.SpkTreads
    | Item.ArmTreads
    | Item.AdvTreads
    | Item.MedTreads
    | Item.ImpMediumTreads
    | Item.SpkMediumTreads
    | Item.ArmMediumTreads
    | Item.HvyTreads
    | Item.AdvMediumTreads
    | Item.EnhArmoredMediumTreads
    | Item.ImpHeavyTreads
    | Item.HvySiegeTreads
    | Item.SpkHeavyTreads
    | Item.BiometalMediumTreads
    | Item.ArmHeavyTreads
    | Item.AdvHeavyTreads
    | Item.ImpHeavySiegeTreads
    | Item.CentriumHeavyTreads
    | Item.Megatreads
    | Item.BiometalHeavyTreads
    | Item.ExpBiometalHeavyTreads
    | Item.EnhArmoredHeavyTreads
    | Item.AdvHeavySiegeTreads
    | Item.HdnCentriumHeavyTreads
    | Item.ExpBiometalMediumTreads -> Propulsion Treads
    | Item.AluminumLeg
    | Item.ImpAluminumLeg
    | Item.CarbonfiberLeg
    | Item.TitaniumLeg
    | Item.VssLeg
    | Item.ImpCarbonfiberLeg
    | Item.ImpTitaniumLeg
    | Item.MakLeg
    | Item.FlexicarbonLeg
    | Item.ArmLeg
    | Item.ImpVssLeg
    | Item.ZioCompositeLegI
    | Item.EnhFlexicarbonLeg
    | Item.EnhArmoredLeg
    | Item.MyomerLeg
    | Item.AdvVssLeg
    | Item.AdvMyomerLeg
    | Item.ExpFlexicarbonLeg
    | Item.ZioCompositeLegIi
    | Item.EtherialTendrils
    | Item.BiometalLeg
    | Item.EnhBiometalLeg
    | Item.ExpMyomerLeg
    | Item.TrollExoskeleton
    | Item.AsbAlloyLeg
    | Item.CentriumLeg
    | Item.HdnCentriumLeg
    | Item.ExpBiometalLeg
    | Item.SigixExoskeleton
    | Item.ZioSupercompositeLeg
    | Item.PotentialLeg
    | Item.MyomerExoskeleton -> Propulsion Legs
    | Item.Wheel
    | Item.ComWheel
    | Item.ArmWheel
    | Item.ArmHugeWheel
    | Item.CentriumWheel
    | Item.HdnCentriumWheel -> Propulsion Wheel
    | Item.HoverUnit
    | Item.BackupPropulsionI
    | Item.ImpHoverUnit
    | Item.Airjet
    | Item.AerolevUnit
    | Item.AsbHoverUnit
    | Item.BackupPropulsionIii
    | Item.GravmagSystem
    | Item.AsbHoverSystem
    | Item.ImpAirjet
    | Item.CldAirjet
    | Item.ImpGravmagSystem
    | Item.CldAerolevUnit
    | Item.CmbAirjet
    | Item.GravmagArray
    | Item.MakHoverUnit
    | Item.ZioGlidesysI
    | Item.AntigravSystem
    | Item.GyrokineticInverter
    | Item.LinearGravjet
    | Item.CldGravmagSystem
    | Item.CmbGravmagSystem
    | Item.ImpAntigravSystem
    | Item.ImpGyrokineticInverter
    | Item.ImpLinearGravjet
    | Item.BackupPropulsionVii
    | Item.ZioGlidesysIi
    | Item.CldAntigravSystem
    | Item.CmbAntigravSystem
    | Item.AntigravArray
    | Item.ExpGyrokineticInverter
    | Item.CldLinearGravjet
    | Item.CmbLinearGravjet -> Propulsion Hover
    | Item.FlightUnit
    | Item.VtolModule
    | Item.ImpFlightUnit
    | Item.CesiumionThruster
    | Item.SurgeThruster
    | Item.ImpVtolModule
    | Item.XenonBombardmentThruster
    | Item.ImpCesiumionThruster
    | Item.CldVtolModule
    | Item.MakFlightUnit
    | Item.NuclearPulseThruster
    | Item.ImpSurgeThruster
    | Item.MniNuclearPulseThruster
    | Item.CldCesiumionThruster
    | Item.BiomechanicalWings
    | Item.FieldPropulsionDrive
    | Item.CldNuclearPulseThruster
    | Item.ExpCesiumionThruster
    | Item.NuclearPulseArray
    | Item.MakMicrothruster
    | Item.ImpulseThruster
    | Item.AdvSurgeThruster
    | Item.CldFieldPropulsionDrive
    | Item.FieldPropulsionArray
    | Item.DiametricDrive
    | Item.FlyingFortressV7
    | Item.Tthruster
    | Item.IntegratedTrackerDrive
    | Item.EtherialPropulsion
    | Item.Qthruster
    | Item.ElectronDiverter
    | Item.ImpDiametricDrive
    | Item.CldImpulseThruster
    | Item.ImpulseThrusterArray
    | Item.ImpQthruster
    | Item.CldQthruster
    | Item.ExpQthruster -> Propulsion Flight
    | Item.Desublimator
    | Item.PowerAmplifier
    | Item.AdvPowerAmplifier
    | Item.ExpPowerAmplifier
    | Item.ThermalGenerator
    | Item.ImpThermalGenerator
    | Item.AdvThermalGenerator
    | Item.ExpThermalGenerator
    | Item.CryofiberWeb
    | Item.ImpCryofiberWeb
    | Item.AdvCryofiberWeb
    | Item.HeatSink
    | Item.ImpHeatSink
    | Item.AdvHeatSink
    | Item.ExpHeatSink
    | Item.CoolingSystem
    | Item.ImpCoolingSystem
    | Item.AdvCoolingSystem
    | Item.ExpCoolingSystem
    | Item.CoolantNetwork
    | Item.AsbNanovents
    | Item.FrostArray
    | Item.DisposableHeatSink
    | Item.CoolantInjector
    | Item.ImpCoolantInjector
    | Item.AdvCoolantInjector
    | Item.ExpCoolantInjector -> Utility Device
    | Item.SmlStorageUnit
    | Item.MedStorageUnit
    | Item.LrgStorageUnit
    | Item.HcpStorageUnit
    | Item.HugeStorageUnit
    | Item.CargoStorageUnit
    | Item.Humpback
    | Item.Lightpack20
    | Item.SmlBattery
    | Item.MedBattery
    | Item.LrgBattery
    | Item.HcpBattery
    | Item.ComBattery
    | Item.EnergyWell
    | Item.ImpEnergyWell
    | Item.AdvEnergyWell
    | Item.ExpEnergyWell
    | Item.ZioBiocell
    | Item.AsbBiocellArray
    | Item.ZioBiocellArray
    | Item.Superbattery
    | Item.SmlMatterPod
    | Item.MedMatterPod
    | Item.LrgMatterPod
    | Item.HcpMatterPod
    | Item.ComMatterPod
    | Item.MatterCompressor
    | Item.ImpMatterCompressor
    | Item.AdvMatterCompressor
    | Item.ExpMatterCompressor
    | Item.Yiuf0sBottomlessMatterPit -> Utility Storage
    | Item.WeightRedistSystem
    | Item.AdvWeightRedistSystem
    | Item.GravityNeutralizer
    | Item.AdvGravityNeutralizer
    | Item.QuantumShadingMachine
    | Item.AsbSuspensionFrame
    | Item.AdvQuantumShadingMachine
    | Item.AsbMetafiberNetwork
    | Item.ZioMetafieldGenerator
    | Item.StFieldCompressor
    | Item.StructuralScanner
    | Item.TrapScanner
    | Item.ImpTrapScanner
    | Item.MakTrapScanner
    | Item.AdvTrapScanner
    | Item.MachineAnalyzer
    | Item.Triangulator
    | Item.VisualProcessingUnit
    | Item.AdvVisualProcessingUnit
    | Item.EnhOpticalArray
    | Item.ExpOpticalArray
    | Item.SpectralAnalyzer
    | Item.SensorArray
    | Item.ImpSensorArray
    | Item.AdvSensorArray
    | Item.LrnSensorArray
    | Item.MakSensorArray
    | Item.ExpSensorArray -> Utility Device
    | Item.SignalInterpreter
    | Item.ImpSignalInterpreter
    | Item.AdvSignalInterpreter
    | Item.ExpSignalInterpreter
    | Item.ActiveSensorSuite -> Utility Processor
    | Item.TerrainScanner
    | Item.ImpTerrainScanner
    | Item.AdvTerrainScanner
    | Item.MakTerrainScanner
    | Item.LrnTerrainScanner
    | Item.ExpTerrainScanner
    | Item.Surveybot24Scanner -> Utility Device
    | Item.TerrainScanProcessor
    | Item.ImpTerrainScanProcessor
    | Item.MakTerrainScanProcessor
    | Item.AdvTerrainScanProcessor
    | Item.ExpTerrainScanProcessor
    | Item.Surveybot24Chip -> Utility Processor
    | Item.SeismicDetector -> Utility Device
    | Item.TransportNetworkCoupler
    | Item.ModifiedTnc
    | Item.B10DecoderChipgeneric
    | Item.B10DecoderChiplooter
    | Item.B10DecoderChipscout
    | Item.B10DecoderChipskirmisher
    | Item.B10AlertChip
    | Item.SalvageTargetingComputer
    | Item.ImpSalvageTargetingComputer
    | Item.MakSalvageTargetingComputer
    | Item.AdvSalvageTargetingComputer
    | Item.AsbCombatSuite
    | Item.TargetingComputer
    | Item.ImpTargetingComputer
    | Item.AdvTargetingComputer
    | Item.ExpTargetingComputer
    | Item.TacticalCoordinationSuite
    | Item.MeleeAnalysisSuite
    | Item.ImpMeleeAnalysisSuite
    | Item.AdvMeleeAnalysisSuite
    | Item.ExpMeleeAnalysisSuite
    | Item.LauncherGuidanceComputer
    | Item.ImpLauncherGuidanceComputer
    | Item.AdvLauncherGuidanceComputer
    | Item.TargetAnalyzer
    | Item.ImpTargetAnalyzer
    | Item.AdvTargetAnalyzer
    | Item.ExpTargetAnalyzer
    | Item.CoreAnalyzer
    | Item.ExpCoreAnalyzer
    | Item.ArmorIntegrityAnalyzer
    | Item.ImpArmorIntegrityAnalyzer
    | Item.ExpArmorIntegrityAnalyzer -> Utility Processor
    | Item.RecoilStabilizer
    | Item.RecoilNullifier
    | Item.MatterFilter
    | Item.PrcMatterFilter
    | Item.EnergyFilter
    | Item.PrcEnergyFilter
    | Item.ParticleCharger
    | Item.ImpParticleCharger
    | Item.AdvParticleCharger
    | Item.ParticleAccelerator
    | Item.ImpParticleAccelerator
    | Item.AdvParticleAccelerator
    | Item.Kinecellerator
    | Item.ImpKinecellerator
    | Item.AdvKinecellerator
    | Item.LauncherLoader
    | Item.QuantumCapacitor
    | Item.WeaponCycler
    | Item.ImpWeaponCycler
    | Item.AdvWeaponCycler
    | Item.ExpWeaponCycler
    | Item.Microactuators
    | Item.Nanoactuators
    | Item.Femtoactuators
    | Item.ActuatorArray
    | Item.ImpActuatorArray
    | Item.AdvActuatorArray
    | Item.ExpActuatorArray
    | Item.ForceBooster
    | Item.ImpForceBooster
    | Item.AdvForceBooster
    | Item.StasisCanceller
    | Item.TransmissionJammer
    | Item.MakTransmissionJammer
    | Item.ImpTransmissionJammer
    | Item.AdvTransmissionJammer
    | Item.ExpTransmissionJammer
    | Item.EcmSuite
    | Item.MakEcmSuite
    | Item.AdvEcmSuite
    | Item.ExpEcmSuite
    | Item.ReactionControlSystem
    | Item.ImpReactionControlSystem
    | Item.AdvReactionControlSystem
    | Item.ExpReactionControlSystem
    | Item.PhaseShifter
    | Item.ImpPhaseShifter
    | Item.AdvPhaseShifter
    | Item.ExpPhaseShifter
    | Item.CloakingDevice
    | Item.MakCloakingDevice
    | Item.ImpCloakingDevice
    | Item.AdvCloakingDevice
    | Item.ExpCloakingDevice
    | Item.CloakOfProtection
    | Item.Shad0sCloak -> Utility Device
    | Item.CoreShielding
    | Item.ImpCoreShielding
    | Item.ExpCoreShielding
    | Item.PowerShielding
    | Item.ImpPowerShielding
    | Item.ExpPowerShielding
    | Item.PropulsionShielding
    | Item.ImpPropulsionShielding
    | Item.ExpPropulsionShielding
    | Item.UtilityShielding
    | Item.ImpUtilityShielding
    | Item.ExpUtilityShielding
    | Item.WeaponShielding
    | Item.ImpWeaponShielding
    | Item.ExpWeaponShielding
    | Item.ZioWeaponCasing
    | Item.LgtArmorPlating
    | Item.MedArmorPlating
    | Item.HvyArmorPlating
    | Item.ZioLightCarapace
    | Item.ZioHeavyCarapace
    | Item.HrdLightArmorPlating
    | Item.HrdMediumArmorPlating
    | Item.HrdHeavyArmorPlating
    | Item.ImpLightArmorPlating
    | Item.ImpMediumArmorPlating
    | Item.ImpHeavyArmorPlating
    | Item.LyrLightArmorPlating
    | Item.MakArmorPlating
    | Item.LyrMediumArmorPlating
    | Item.LyrHeavyArmorPlating
    | Item.CentriumLightArmorPlating
    | Item.CentriumMediumArmorPlating
    | Item.CentriumHeavyArmorPlating
    | Item.CentriumLinkedPlating
    | Item.ReactivePlating
    | Item.MedReactivePlating
    | Item.MakKineticPlating
    | Item.HvyReactivePlating
    | Item.ReflectivePlating
    | Item.MedReflectivePlating
    | Item.MakThermalPlating
    | Item.HvyReflectivePlating
    | Item.BrawnsArmorth
    | Item.BrawnsArmorex
    | Item.InsulatedPlating
    | Item.MedInsulatedPlating
    | Item.HvyInsulatedPlating
    | Item.DamperPlating
    | Item.ZioShadeCarapace
    | Item.ZioShadeArmor
    | Item.AsbAlloyArmor
    | Item.MakAblativeArmor
    | Item.ActiveCoolingArmor
    | Item.PoweredArmor
    | Item.ImpPoweredArmor
    | Item.AdvPoweredArmor
    | Item.ExpPoweredArmor
    | Item.IcutusBuckler
    | Item.LgtRegenerativePlating
    | Item.MedRegenerativePlating
    | Item.HvyRegenerativePlating
    | Item.ShellArmor
    | Item.PhaseArmor
    | Item.GrapheneBrace
    | Item.FocalShield
    | Item.ImpFocalShield
    | Item.AdvFocalShield
    | Item.ExpFocalShield
    | Item.ThermalShield
    | Item.ImpThermalShield
    | Item.AdvThermalShield
    | Item.ExpThermalShield
    | Item.ThermalBarrier
    | Item.BeamSplitter
    | Item.ThermalDefenseSuite
    | Item.ImpThermalDefenseSuite
    | Item.AdvThermalDefenseSuite
    | Item.ExpThermalDefenseSuite
    | Item.ShockAbsorptionSystem
    | Item.ImpShockAbsorptionSystem
    | Item.ExpShockAbsorptionSystem
    | Item.EmDisruptionField
    | Item.AdvEmDisruptionField
    | Item.ExpEmDisruptionField
    | Item.MerlnsChromaticScreen
    | Item.HardlightGenerator
    | Item.ImpHardlightGenerator
    | Item.AdvHardlightGenerator
    | Item.ExpHardlightGenerator
    | Item.ShieldGenerator
    | Item.ImpShieldGenerator
    | Item.AdvShieldGenerator
    | Item.ExpShieldGenerator
    | Item.ForceField
    | Item.ImpForceField
    | Item.AdvForceField
    | Item.ExpForceField
    | Item.TvrtlsUltimateField
    | Item.VortexFieldProjector
    | Item.RemoteShield
    | Item.ImpRemoteShield
    | Item.AdvRemoteShield
    | Item.RemoteForceField
    | Item.ImpRemoteForceField
    | Item.EnergyMantle
    | Item.ImpEnergyMantle
    | Item.AegisRemoteShield
    | Item.PhaseRedirector
    | Item.PointDefenseSystem
    | Item.PointDefenseArray
    | Item.AntimissileSystem -> Utility Armor
    | Item.ExChip1
    | Item.HackingSuite
    | Item.MakHackingSuite
    | Item.ImpHackingSuite
    | Item.AdvHackingSuite
    | Item.ExpHackingSuite
    | Item.SystemMapper
    | Item.DeepNetworkScanner
    | Item.ArchitectGodChipA
    | Item.ExChip2
    | Item.SystemShield
    | Item.MakSystemShield
    | Item.ImpSystemShield
    | Item.AdvSystemShield
    | Item.ExpSystemShield
    | Item.GhostBarrier
    | Item.QuantumRouter
    | Item.ArchitectGodChipD
    | Item.Authchiprnc
    | Item.Authchiprcombat
    | Item.Authchippower
    | Item.Authchippropulsion
    | Item.Authchipdevice
    | Item.Authchipstorage
    | Item.Authchipprocessor
    | Item.Authchiparmor
    | Item.Authchipweapon
    | Item.RelayCouplernc
    | Item.RelayCouplerc
    | Item.RelayCouplerarc
    | Item.RelayCouplerswarmer
    | Item.RelayCouplercutter
    | Item.RelayCouplergrunt
    | Item.RelayCouplerbrawler
    | Item.RelayCouplerduelist
    | Item.RelayCouplersentry
    | Item.RelayCouplerdemolisher
    | Item.RelayCouplerspecialist
    | Item.RelayCouplerhunter
    | Item.RelayCouplerheavy
    | Item.RelayCouplerbehemoth
    | Item.RelayCouplerprogrammer -> Utility Processor
    | Item.SkeletonBox
    | Item.O1mtfsAutohacker
    | Item.ComponentAnalysisSuite
    | Item.ImpComponentAnalysisSuite
    | Item.AdvComponentAnalysisSuite
    | Item.DynamicInsulationSystem
    | Item.ImpDynamicInsulationSystem
    | Item.AdvDynamicInsulationSystem
    | Item.SystemGuard
    | Item.ImpSystemGuard
    | Item.ExpSystemGuard
    | Item.CorruptionScreen
    | Item.ImpCorruptionScreen
    | Item.AdvCorruptionScreen
    | Item.SystemRestorationModule
    | Item.MakSystemRestorationModule
    | Item.ImpSystemRestorationModule
    | Item.AdvSystemRestorationModule
    | Item.SystemPurifier
    | Item.ExpSystemPurifier
    | Item.TractorBeam
    | Item.HpwTractorBeam
    | Item.LrnTractorBeam
    | Item.MobileRefineryMkCclxvii
    | Item.TrapExtractor
    | Item.ImpTrapExtractor
    | Item.AdvTrapExtractor
    | Item.TrapReconfigurator
    | Item.Recalibrator
    | Item.ImpRecalibrator
    | Item.AdvRecalibrator
    | Item.FieldRecyclingUnit
    | Item.ImpFieldRecyclingUnit
    | Item.AdvFieldRecyclingUnit
    | Item.ExpFieldRecyclingUnit
    | Item.DroneBay
    | Item.ZdroneBay
    | Item.MniDroneBay
    | Item.MappingDroneBay
    | Item.AdvDroneBay
    | Item.BombDroneBay
    | Item.ThiefDroneBay
    | Item.DecoyDroneBay
    | Item.SpliceDroneBay
    | Item.CombatDroneBay
    | Item.AssaultDroneBay
    | Item.StealthDroneBay
    | Item.SwarmDroneBay
    | Item.SupersonicDroneBay
    | Item.SensorDroneBay
    | Item.HackingDroneBay
    | Item.MinesnifferDroneBay
    | Item.Armyinabox
    | Item.WardroneBay
    | Item.BombFactoryNo2
    | Item.MobileAssemblyUnit
    | Item.HeartOfSteel
    | Item.GolemUnit
    | Item.PsuRigger
    | Item.PhasingAfg
    | Item.AsneutralizerNo17b
    | Item.Chronowheel
    | Item.DimensionalNodeInitializer
    | Item.TransdimensionalReconstructor
    | Item.HpwTransdimensionalReconstructor
    | Item.CoreExpander
    | Item.CoreRegenerator
    | Item.IntegrityRedistributor
    | Item.IntegratedDissipator
    | Item.SuperchargedIntegratedDissipator
    | Item.IntegratedThermoelectricNetwork
    | Item.IntegratedReactor
    | Item.SuperchargedIntegratedReactor
    | Item.IntegratedMediator
    | Item.CoreMembrane
    | Item.NavigationEfficiencyMatrix
    | Item.CoreResetMatrix
    | Item.SubatomicReplicator
    | Item.Terrabomb
    | Item.CorePhysicsCalibrator
    | Item.SpacefoldActivator
    | Item.MicrowarpDrive
    | Item.LcCapacitor
    | Item.LrcArmor
    | Item.LrcStorage
    | Item.LrcEnergyWell
    | Item.LrcMatterCompressor
    | Item.LrcBoosters
    | Item.LrcInsulator -> Utility Device
    | Item.EmPulseGun
    | Item.HvyEmPulseGun
    | Item.EmShotgun
    | Item.ImpEmShotgun
    | Item.ShockRifle
    | Item.RiotGun
    | Item.HvyEmShotgun
    | Item.LightningGun
    | Item.HvyRiotGun
    | Item.ArcProjector
    | Item.PrcShockRifle
    | Item.HpwShockRifle
    | Item.ArcThrower
    | Item.ImpLightningGun
    | Item.TeslaRifle
    | Item.ImpArcProjector
    | Item.HvyTeslaRifle
    | Item.HypEmGaussRifle
    | Item.ImpArcThrower
    | Item.O1mtfsShockpuncher
    | Item.GammaRifle
    | Item.TachyonDispersionRay
    | Item.Immobilizer
    | Item.ModifiedEmGaussRifle
    | Item.Awsexdec
    | Item.EnhGammaRifle
    | Item.MedLaser
    | Item.SmlLaser
    | Item.BackupLaserI
    | Item.BeamRifle
    | Item.ParticleGun
    | Item.SpreadLaser
    | Item.ImpMediumLaser
    | Item.FieldLaser
    | Item.PulseRifle
    | Item.BackupLaserIii
    | Item.HvyParticleGun
    | Item.PrcBeamRifle
    | Item.AdvBeamRifle
    | Item.HvyLaser
    | Item.GatlingLaser
    | Item.CldPulseRifle
    | Item.HpwFieldLaser
    | Item.ImpSpreadLaser
    | Item.MakLaser
    | Item.PlasmaRifle
    | Item.ThermicLaser
    | Item.Beamcaster
    | Item.ForceRifle
    | Item.ImpHeavyLaser
    | Item.StormLaser
    | Item.ZioLasers
    | Item.WaveGun
    | Item.VariableChargeGun
    | Item.HvyBeamcaster
    | Item.CldPlasmaRifle
    | Item.EnhForceRifle
    | Item.HvyGatlingLaser
    | Item.ZioPhasers
    | Item.PhaseGun
    | Item.DispersionRifle
    | Item.BackupLaserVii
    | Item.PlasmaStorm
    | Item.AdvPlasmaRifle
    | Item.HvyWaveGun
    | Item.AdvVariableChargeGun
    | Item.CldPhaseGun
    | Item.LrnGatlingLaser
    | Item.WarpGun
    | Item.VortexRifle
    | Item.ZioLaserm
    | Item.Awsthermal
    | Item.PdLaser
    | Item.QuantumRifle
    | Item.PrcPhaseGun
    | Item.HvyDispersionRifle
    | Item.VortexShotgun
    | Item.VortexRail
    | Item.ZioPhaserm
    | Item.EnhQuantumRifle
    | Item.ZioLaserh
    | Item.HvyQuantumRifle
    | Item.ZioPhaserh
    | Item.GatlingBeam
    | Item.SigixSheargun
    | Item.ModifiedSigixSheargun -> Weapon Gun
    | Item.LgtEmPulseCannon
    | Item.EmPulseCannon
    | Item.ImpEmPulseCannon
    | Item.ProtonCannon
    | Item.LrnProtonCannon
    | Item.DisruptorCannon
    | Item.HvyProtonCannon
    | Item.HerfCannon
    | Item.HvyDisruptorCannon
    | Item.CldProtonCannon
    | Item.ProtonBurstCannon
    | Item.ComHerfCannon
    | Item.LatentEnergyStreamer
    | Item.Nk0lasTeslaDoomcannon
    | Item.Emds
    | Item.HpwDisruptorCannon
    | Item.BeamCannon
    | Item.ParticleCannon
    | Item.AdvBeamCannon
    | Item.HvyParticleCannon
    | Item.IonCannon
    | Item.PlasmaCannon
    | Item.HvyIonCannon
    | Item.CldParticleCannon
    | Item.PhaseCannon
    | Item.HvyPlasmaCannon
    | Item.CldPlasmaCannon
    | Item.ComIonCannon
    | Item.IonBurstCannon
    | Item.AdvPlasmaCannon
    | Item.HvyPhaseCannon
    | Item.NeutronCannon
    | Item.MatterNeutralizer
    | Item.HvyNeutronCannon
    | Item.LrnPhaseCannon
    | Item.CldPhaseCannon
    | Item.VortexCannon
    | Item.GuiPlasmaCannon
    | Item.NovaCannon
    | Item.ImpMatterNeutralizer
    | Item.VortexDriver
    | Item.ZioAlphaCannon
    | Item.AsbFocalCannon
    | Item.EnhNovaCannon
    | Item.Firepult
    | Item.YoloCannon
    | Item.PotentialCannon
    | Item.WarpCannon
    | Item.CldNovaCannon
    | Item.NullCannon
    | Item.ImpPotentialCannon
    | Item.Disintegrator
    | Item.CoreCannon
    | Item.SigixShearcannon
    | Item.DrainedLcannon
    | Item.Lcannon
    | Item.ZioAlphaCannonMkIi
    | Item.Bfg9kVortexEdition -> Weapon Cannon
    | Item.AssaultRifle
    | Item.AsbRifle
    | Item.LgtAssaultRifle
    | Item.HvyAssaultRifle
    | Item.Autogun
    | Item.Shotgun
    | Item.BattleRifle
    | Item.AsbHeavyRifle
    | Item.ImpAssaultRifle
    | Item.Minigun
    | Item.HpwShotgun
    | Item.AsbShotgun
    | Item.BarrageGun
    | Item.EnhAutogun
    | Item.GaussRifle
    | Item.AsbGaussRifle
    | Item.FlakGun
    | Item.PrcAssaultRifle
    | Item.HvyBattleRifle
    | Item.MakShrapnelGun
    | Item.CoilGun
    | Item.HypGaussRifle
    | Item.HvyMachineGun
    | Item.ImpHeavyMachineGun
    | Item.ComGaussRifle
    | Item.XlAutogunSubcomponent
    | Item.KePenetrator
    | Item.HypCoilGun
    | Item.ImpKePenetrator
    | Item.EnhCoilGun
    | Item.ComCoilGun
    | Item.Railgun
    | Item.AdvKePenetrator
    | Item.LinkedAutogun
    | Item.Awsgauss
    | Item.HypRailgun
    | Item.HelicalRailgun
    | Item.ComRailgun
    | Item.XlAutogunArray
    | Item.AshsBoomstick
    | Item.BrawnsBoregun
    | Item.Multirail
    | Item.HypMultirail
    | Item.Shad0sSniperRifle
    | Item.A3sSniperRifle -> Weapon Gun
    | Item.LgtCannon
    | Item.ImpLightCannon
    | Item.BattleCannon
    | Item.AssaultCannon
    | Item.HvyAssaultCannon
    | Item.FlakCannon
    | Item.AdvAssaultCannon
    | Item.GaussCannon
    | Item.SlugCannon
    | Item.MniAssaultCannon
    | Item.MagneticAccelerationCannon
    | Item.HvyFlakCannon
    | Item.BoreCannon
    | Item.AntimatterCannon
    | Item.MassDriver
    | Item.HvyMassDriver
    | Item.EnhGaussCannon
    | Item.HypGaussCannon
    | Item.TrirailAccelerator
    | Item.HardcellCannon
    | Item.HvyGaussCannon
    | Item.HypMassDriver
    | Item.HvyAutocannon
    | Item.DasCannon
    | Item.LgtAntimatterCannon
    | Item.LinearAccelerator
    | Item.HvyLinearAccelerator
    | Item.ComMassDriver
    | Item.HvyHardcellCannon
    | Item.ComLinearAccelerator
    | Item.HypLinearAccelerator
    | Item.HclLinearAccelerator
    | Item.GravitonCannon
    | Item.BlastCannon
    | Item.P13cesGatlingFlakker
    | Item.Awsautocannon
    | Item.Perforator
    | Item.OmegaCannon -> Weapon Cannon
    | Item.EmpBlaster
    | Item.ShockBombLauncher
    | Item.AdvEmpBlaster
    | Item.ProtonMissileLauncher
    | Item.ImpProtonMissileLauncher
    | Item.GuiEmpBlaster
    | Item.HvyShockBombLauncher
    | Item.TeslaBombLauncher
    | Item.HvyProtonMissileLauncher
    | Item.ComTeslaBombLauncher
    | Item.GammaBombArray
    | Item.EnhGammaBombArray
    | Item.GrenadeLauncher
    | Item.RocketLauncher
    | Item.MniGrenadeLauncher
    | Item.ImpGrenadeLauncher
    | Item.MissileLauncher
    | Item.ConcussiveRpg
    | Item.Yiuf0sDoublenader
    | Item.HvyRocketLauncher
    | Item.HvyMissileLauncher
    | Item.GuiMissileLauncher
    | Item.PrcGrenadeLauncher
    | Item.RocketArray
    | Item.LrnMissileLauncher
    | Item.ImpConcussiveRpg
    | Item.PrcRocketLauncher
    | Item.ScatterRocketArray
    | Item.SmartbombLauncher
    | Item.MniSmartbombLauncher
    | Item.TiamatMissileLauncher
    | Item.Thermoblaster
    | Item.MicronukeLauncher
    | Item.AdvConcussiveRpg
    | Item.NeutronMissileLauncher
    | Item.FusionBombLauncher
    | Item.HellfireMissileLauncher
    | Item.AdvMicronukeLauncher
    | Item.TacticalQuantumWarhead
    | Item.VortexCatalystActivator
    | Item.ChainMissileLauncher
    | Item.RagnarokMissileLauncher
    | Item.PointSingularityLauncher
    | Item.GuiMicronukeLauncher
    | Item.NinteyNineTntsNukerbomber
    | Item.ZbombDeliverySystem
    | Item.SigixTerminator
    | Item.SuperchargedSigixTerminator
    | Item.ContainmentFacilitator
    | Item.Detonator -> Weapon Launcher
    | Item.DirtyDatajack
    | Item.SpliceInjector
    | Item.Datajack
    | Item.ImpDatajack
    | Item.AdvDatajack
    | Item.RemoteDatajack
    | Item.ImpRemoteDatajack
    | Item.AdvRemoteDatajack
    | Item.ExpRemoteDatajack
    | Item.GuiRemoteDatajack
    | Item.MerlnsWand
    | Item.FieldLobotomyKit
    | Item.MiningLaser
    | Item.WeldingTorch
    | Item.PlasmaCutter
    | Item.ImpPlasmaCutter
    | Item.Flamer
    | Item.AsbFtorch
    | Item.EnhFlamer
    | Item.PlasmaFlamer
    | Item.AsbPtorch
    | Item.Run14sThrowingClaymores
    | Item.Run14sThrowingClaymoresV3
    | Item.Ad0rfsMagmablaster
    | Item.StasisBeam
    | Item.StasisProjector
    | Item.ExpStasisProjector
    | Item.MolecularDeconstructor -> Weapon Special
    | Item.Hammer
    | Item.Mace
    | Item.Flail
    | Item.Maul
    | Item.AsbMaul
    | Item.HvyHammer
    | Item.HvyMace
    | Item.HvyFlail
    | Item.GreatMaul
    | Item.PoweredHammer
    | Item.MakHammer
    | Item.PowerMaul
    | Item.AsbPmaul
    | Item.ImpactMace
    | Item.ShockMaul
    | Item.ThunderHammer
    | Item.Compactor
    | Item.GravityFlail
    | Item.ClanksMallet
    | Item.CoreStripper
    | Item.MiningClaw
    | Item.Ec_1
    | Item.Katana
    | Item.AsbBlade
    | Item.Scythe
    | Item.Axe
    | Item.BladeSaw
    | Item.Ec_3
    | Item.Chainsword
    | Item.Ripper
    | Item.MakAxe
    | Item.MakSword
    | Item.GreatAxe
    | Item.Greatsword
    | Item.PowerSword
    | Item.AsbPsword
    | Item.Falx
    | Item.CarbideSaw
    | Item.Segregator
    | Item.Tearclaws
    | Item.Ec_5
    | Item.PhasingSabre
    | Item.PlasmaSword
    | Item.IonicAxe
    | Item.MniTearclaws
    | Item.DualbladeSaw
    | Item.Vibroblade
    | Item.MolecularScythe
    | Item.CentriumGreatsword
    | Item.MasterTearclaws
    | Item.Longsword1
    | Item.Ec_7
    | Item.Nanosword
    | Item.ParticleCleaver
    | Item.CentriumClaws
    | Item.IcutusSwordlootmaker
    | Item.IcutusSwordchoppy
    | Item.VortexShredder
    | Item.Ec_9
    | Item.SigixBroadsword
    | Item.Spear
    | Item.MakSpear
    | Item.Cra16sPointyStick
    | Item.HvyPick
    | Item.Lance
    | Item.KineticSpear
    | Item.ForceLance
    | Item.PlasmaLance
    | Item.EnhForceLance
    | Item.VortexLance
    | Item.Cra16sBehemothSlayer -> Weapon Melee
    | Item.BladeTrap
    | Item.SegregatorTrap
    | Item.ExplosiveTrap
    | Item.HeavyExplosiveTrap
    | Item.TiamatBombTrap
    | Item.FusionBombTrap
    | Item.HellfireTrap
    | Item.ArmageddonTrap
    | Item.DirtyBombTrap
    | Item.EmpTrap
    | Item.ProtonBombTrap
    | Item.TeslaBombTrap
    | Item.GammaBombTrap
    | Item.ShockTrap
    | Item.EmSurgeTrap
    | Item.FireTrap
    | Item.StasisTrap
    | Item.SignalGenerator
    | Item.SelfdestructInterrupter
    | Item.SapperCharge
    | Item.Deployasentry
    | Item.GalModule
    | Item.PortableAfg
    | Item.SgempPrototype
    | Item.TerrabombDerivative
    | Item.SigixContainmentPod
    | Item.SigixCorpse
    | Item.Meganuke
    | Item.GammaRefractor -> Misc

let itemToChar (item: Item) : string =
    match itemToCategory item with
    | Matter -> "%"
    | Propulsion _ -> "="
    | Power -> "*"
    | Misc -> "~"
    | Utility _ -> "!"
    | Weapon weapon ->
        match weapon with
        | Cannon -> "]"
        | Launcher -> "]"
        | Gun -> "["
        | Melee -> "/"
        | Special -> "~"

type Occupancy =
    | Obstructed
    | Vacant
    | Occupied of LuigiEntity

let mapTileOccupancy (tile: LuigiTile) =
    match tile.cell with
    | cell.NO_CELL
    | cell.SEALED_DOOR
    | cell.DOOR_SAN
    | cell.DOOR_SCR
    | cell.DOOR_MAT
    | cell.DOOR_FAC
    | cell.DOOR_RES
    | cell.DOOR_ACC
    | cell.DOOR_SUR
    | cell.DOOR_MIN
    | cell.DOOR_EXI
    | cell.DOOR_STO
    | cell.DOOR_REC
    | cell.DOOR_WAS
    | cell.DOOR_GAR
    | cell.DOOR_DSF
    | cell.DOOR_LOW
    | cell.DOOR_UPP
    | cell.DOOR_PRO
    | cell.DOOR_DEE
    | cell.DOOR_ZIO
    | cell.DOOR_DAT
    | cell.DOOR_ZHI
    | cell.DOOR_WAR
    | cell.DOOR_EXT
    | cell.DOOR_CET
    | cell.DOOR_ARC
    | cell.DOOR_HUB
    | cell.DOOR_ARM
    | cell.DOOR_LAB
    | cell.DOOR_QUA
    | cell.DOOR_TES
    | cell.DOOR_SEC
    | cell.DOOR_COM
    | cell.DOOR_AC0
    | cell.DOOR_LAI
    | cell.DOOR_TOW -> Vacant
    | cell.TEMP_WALL
    | cell.WALL_SAN
    | cell.WALL_SCR
    | cell.WALL_MAT
    | cell.WALL_FAC
    | cell.WALL_RES
    | cell.WALL_ACC
    | cell.WALL_SUR
    | cell.WALL_MIN
    | cell.WALL_EXI
    | cell.WALL_STO
    | cell.WALL_REC
    | cell.WALL_WAS
    | cell.WALL_GAR
    | cell.WALL_DSF
    | cell.WALL_LOW
    | cell.WALL_UPP
    | cell.WALL_PRO
    | cell.WALL_DEE
    | cell.WALL_ZIO
    | cell.WALL_DAT
    | cell.WALL_ZHI
    | cell.WALL_WAR
    | cell.WALL_EXT
    | cell.WALL_CET
    | cell.WALL_ARC
    | cell.WALL_HUB
    | cell.WALL_ARM
    | cell.WALL_LAB
    | cell.WALL_QUA
    | cell.WALL_TES
    | cell.WALL_SEC
    | cell.WALL_COM
    | cell.WALL_AC0
    | cell.WALL_LAI
    | cell.WALL_TOW
    | cell.EARTH
    | cell.EARTH_EXC -> Obstructed
    | cell.FLOOR_SAN
    | cell.FLOOR_SCR
    | cell.FLOOR_MAT
    | cell.FLOOR_FAC
    | cell.FLOOR_RES
    | cell.FLOOR_ACC
    | cell.FLOOR_SUR
    | cell.FLOOR_MIN
    | cell.FLOOR_EXI
    | cell.FLOOR_STO
    | cell.FLOOR_REC
    | cell.FLOOR_WAS
    | cell.FLOOR_GAR
    | cell.FLOOR_DSF
    | cell.FLOOR_LOW
    | cell.FLOOR_UPP
    | cell.FLOOR_PRO
    | cell.FLOOR_DEE
    | cell.FLOOR_ZIO
    | cell.FLOOR_DAT
    | cell.FLOOR_ZHI
    | cell.FLOOR_WAR
    | cell.FLOOR_EXT
    | cell.FLOOR_CET
    | cell.FLOOR_ARC
    | cell.FLOOR_HUB
    | cell.FLOOR_ARM
    | cell.FLOOR_LAB
    | cell.FLOOR_QUA
    | cell.FLOOR_TES
    | cell.FLOOR_SEC
    | cell.FLOOR_COM
    | cell.FLOOR_AC0
    | cell.FLOOR_LAI
    | cell.FLOOR_TOW
    | cell.GROUND -> Vacant
    | cell.STAIRS_SAN
    | cell.STAIRS_SCR
    | cell.STAIRS_MAT
    | cell.STAIRS_FAC
    | cell.STAIRS_RES
    | cell.STAIRS_SUR
    | cell.STAIRS_ACC
    | cell.STAIRS_MIN
    | cell.STAIRS_EXI
    | cell.STAIRS_STO
    | cell.STAIRS_REC
    | cell.STAIRS_WAS
    | cell.STAIRS_GAR
    | cell.STAIRS_DSF
    | cell.STAIRS_LOW
    | cell.STAIRS_UPP
    | cell.STAIRS_PRO
    | cell.STAIRS_DEE
    | cell.STAIRS_ZIO
    | cell.STAIRS_DAT
    | cell.STAIRS_ZHI
    | cell.STAIRS_WAR
    | cell.STAIRS_EXT
    | cell.STAIRS_CET
    | cell.STAIRS_ARC
    | cell.STAIRS_HUB
    | cell.STAIRS_ARM
    | cell.STAIRS_LAB
    | cell.STAIRS_QUA
    | cell.STAIRS_TES
    | cell.STAIRS_SEC
    | cell.STAIRS_COM
    | cell.STAIRS_AC0
    | cell.STAIRS_LAI
    | cell.STAIRS_TOW
    | cell.STAIRS_NOACCESS
    | cell.STAIRS_BLOCKED
    | cell.STAIRS_GAR_OPEN
    | cell.STAIRS_DSF_OPEN
    | cell.STAIRS_SHORTCUT -> Vacant
    | cell.SHORTCUT_SAN
    | cell.SHORTCUT_SCR
    | cell.SHORTCUT_MAT
    | cell.SHORTCUT_FAC
    | cell.SHORTCUT_RES
    | cell.SHORTCUT_ACC
    | cell.SHORTCUT_SUR
    | cell.SHORTCUT_MIN
    | cell.SHORTCUT_EXI
    | cell.SHORTCUT_STO
    | cell.SHORTCUT_REC
    | cell.SHORTCUT_WAS
    | cell.SHORTCUT_GAR
    | cell.SHORTCUT_DSF
    | cell.SHORTCUT_LOW
    | cell.SHORTCUT_UPP
    | cell.SHORTCUT_PRO
    | cell.SHORTCUT_DEE
    | cell.SHORTCUT_ZIO
    | cell.SHORTCUT_DAT
    | cell.SHORTCUT_ZHI
    | cell.SHORTCUT_WAR
    | cell.SHORTCUT_EXT
    | cell.SHORTCUT_CET
    | cell.SHORTCUT_ARC
    | cell.SHORTCUT_HUB
    | cell.SHORTCUT_ARM
    | cell.SHORTCUT_LAB
    | cell.SHORTCUT_QUA
    | cell.SHORTCUT_TES
    | cell.SHORTCUT_SEC
    | cell.SHORTCUT_COM
    | cell.SHORTCUT_AC0
    | cell.SHORTCUT_LAI
    | cell.SHORTCUT_TOW
    | cell.SHORTCUT_KNOWN -> Vacant
    | _ -> Obstructed // bad
    |> function
        | Occupied _ -> raise (System.Exception("invalid occupancy state of cell element"))
        | Obstructed -> Obstructed
        | Vacant ->
            // check if entity is present
            match tile.entity with
            | Some entity when entity.entity <> Domain.entity.Cogmind -> Occupied entity
            | _ -> Vacant

    |> function
        | Vacant ->
            // check if prop is blocking
            match tile.propPointer with
            | Some prop ->
                let prop = Domain.getProp prop

                match Domain.propToOcclusion prop with
                | Domain.PropOcclusion.Obstructed -> Obstructed
                | _ -> Vacant
            | None -> Vacant
        | x -> x


let cellToChar (tile: LuigiTile) : string =
    match tile.cell with
    | cell.SEALED_DOOR
    | cell.DOOR_SAN
    | cell.DOOR_SCR
    | cell.DOOR_MAT
    | cell.DOOR_FAC
    | cell.DOOR_RES
    | cell.DOOR_ACC
    | cell.DOOR_SUR
    | cell.DOOR_MIN
    | cell.DOOR_EXI
    | cell.DOOR_STO
    | cell.DOOR_REC
    | cell.DOOR_WAS
    | cell.DOOR_GAR
    | cell.DOOR_DSF
    | cell.DOOR_LOW
    | cell.DOOR_UPP
    | cell.DOOR_PRO
    | cell.DOOR_DEE
    | cell.DOOR_ZIO
    | cell.DOOR_DAT
    | cell.DOOR_ZHI
    | cell.DOOR_WAR
    | cell.DOOR_EXT
    | cell.DOOR_CET
    | cell.DOOR_ARC
    | cell.DOOR_HUB
    | cell.DOOR_ARM
    | cell.DOOR_LAB
    | cell.DOOR_QUA
    | cell.DOOR_TES
    | cell.DOOR_SEC
    | cell.DOOR_COM
    | cell.DOOR_AC0
    | cell.DOOR_LAI
    | cell.DOOR_TOW -> Some "+"
    | cell.TEMP_WALL
    | cell.WALL_SAN
    | cell.WALL_SCR
    | cell.WALL_MAT
    | cell.WALL_FAC
    | cell.WALL_RES
    | cell.WALL_ACC
    | cell.WALL_SUR
    | cell.WALL_MIN
    | cell.WALL_EXI
    | cell.WALL_STO
    | cell.WALL_REC
    | cell.WALL_WAS
    | cell.WALL_GAR
    | cell.WALL_DSF
    | cell.WALL_LOW
    | cell.WALL_UPP
    | cell.WALL_PRO
    | cell.WALL_DEE
    | cell.WALL_ZIO
    | cell.WALL_DAT
    | cell.WALL_ZHI
    | cell.WALL_WAR
    | cell.WALL_EXT
    | cell.WALL_CET
    | cell.WALL_ARC
    | cell.WALL_HUB
    | cell.WALL_ARM
    | cell.WALL_LAB
    | cell.WALL_QUA
    | cell.WALL_TES
    | cell.WALL_SEC
    | cell.WALL_COM
    | cell.WALL_AC0
    | cell.WALL_LAI
    | cell.WALL_TOW
    | cell.EARTH
    | cell.EARTH_EXC -> Some "#"
    | cell.FLOOR_SAN
    | cell.FLOOR_SCR
    | cell.FLOOR_MAT
    | cell.FLOOR_FAC
    | cell.FLOOR_RES
    | cell.FLOOR_ACC
    | cell.FLOOR_SUR
    | cell.FLOOR_MIN
    | cell.FLOOR_EXI
    | cell.FLOOR_STO
    | cell.FLOOR_REC
    | cell.FLOOR_WAS
    | cell.FLOOR_GAR
    | cell.FLOOR_DSF
    | cell.FLOOR_LOW
    | cell.FLOOR_UPP
    | cell.FLOOR_PRO
    | cell.FLOOR_DEE
    | cell.FLOOR_ZIO
    | cell.FLOOR_DAT
    | cell.FLOOR_ZHI
    | cell.FLOOR_WAR
    | cell.FLOOR_EXT
    | cell.FLOOR_CET
    | cell.FLOOR_ARC
    | cell.FLOOR_HUB
    | cell.FLOOR_ARM
    | cell.FLOOR_LAB
    | cell.FLOOR_QUA
    | cell.FLOOR_TES
    | cell.FLOOR_SEC
    | cell.FLOOR_COM
    | cell.FLOOR_AC0
    | cell.FLOOR_LAI
    | cell.FLOOR_TOW
    | cell.GROUND -> Some " "
    | cell.STAIRS_SAN
    | cell.STAIRS_SCR
    | cell.STAIRS_MAT
    | cell.STAIRS_FAC
    | cell.STAIRS_RES
    | cell.STAIRS_SUR
    | cell.STAIRS_ACC
    | cell.STAIRS_MIN
    | cell.STAIRS_EXI
    | cell.STAIRS_STO
    | cell.STAIRS_REC
    | cell.STAIRS_WAS
    | cell.STAIRS_GAR
    | cell.STAIRS_DSF
    | cell.STAIRS_LOW
    | cell.STAIRS_UPP
    | cell.STAIRS_PRO
    | cell.STAIRS_DEE
    | cell.STAIRS_ZIO
    | cell.STAIRS_DAT
    | cell.STAIRS_ZHI
    | cell.STAIRS_WAR
    | cell.STAIRS_EXT
    | cell.STAIRS_CET
    | cell.STAIRS_ARC
    | cell.STAIRS_HUB
    | cell.STAIRS_ARM
    | cell.STAIRS_LAB
    | cell.STAIRS_QUA
    | cell.STAIRS_TES
    | cell.STAIRS_SEC
    | cell.STAIRS_COM
    | cell.STAIRS_AC0
    | cell.STAIRS_LAI
    | cell.STAIRS_TOW
    | cell.STAIRS_NOACCESS
    | cell.STAIRS_BLOCKED
    | cell.STAIRS_GAR_OPEN
    | cell.STAIRS_DSF_OPEN
    | cell.STAIRS_SHORTCUT -> Some ">"
    | cell.SHORTCUT_SAN
    | cell.SHORTCUT_SCR
    | cell.SHORTCUT_MAT
    | cell.SHORTCUT_FAC
    | cell.SHORTCUT_RES
    | cell.SHORTCUT_ACC
    | cell.SHORTCUT_SUR
    | cell.SHORTCUT_MIN
    | cell.SHORTCUT_EXI
    | cell.SHORTCUT_STO
    | cell.SHORTCUT_REC
    | cell.SHORTCUT_WAS
    | cell.SHORTCUT_GAR
    | cell.SHORTCUT_DSF
    | cell.SHORTCUT_LOW
    | cell.SHORTCUT_UPP
    | cell.SHORTCUT_PRO
    | cell.SHORTCUT_DEE
    | cell.SHORTCUT_ZIO
    | cell.SHORTCUT_DAT
    | cell.SHORTCUT_ZHI
    | cell.SHORTCUT_WAR
    | cell.SHORTCUT_EXT
    | cell.SHORTCUT_CET
    | cell.SHORTCUT_ARC
    | cell.SHORTCUT_HUB
    | cell.SHORTCUT_ARM
    | cell.SHORTCUT_LAB
    | cell.SHORTCUT_QUA
    | cell.SHORTCUT_TES
    | cell.SHORTCUT_SEC
    | cell.SHORTCUT_COM
    | cell.SHORTCUT_AC0
    | cell.SHORTCUT_LAI
    | cell.SHORTCUT_TOW
    | cell.SHORTCUT_KNOWN -> Some "<"
    | _ -> None
    |> function
        | Some char ->
            match char with
            | " " ->
                match tile.item with
                | Some item -> itemToChar item.item
                | None ->
                    match tile.entity with
                    | Some entity when entity.entity = Domain.entity.Cogmind -> "@"
                    | Some _ -> "r"
                    | None -> " "
            | _ -> char
        | None -> "?"
    |> function
        | " " ->
            match tile.propPointer with
            | Some pointer -> "X"
            | None -> " "
        | char -> char

let printPath path goal (mapWidth, mapHeight) (tiles: LuigiTile list) =
    for col in 0 .. mapWidth - 1 do
        for row in 0 .. mapHeight - 1 do
            let tile = tiles.[row * mapHeight + col]

            if List.contains tile path then
                match tile.entity with
                | Some entity when entity.entity = Domain.entity.Cogmind -> printf "@"
                | _ when tile = goal -> printf "@"
                | _ -> printf "+"
            else
                printf "%s" (cellToChar tile)

        printfn ""

let playerTile tiles =
    tiles
    |> List.find (fun tile ->
        match tile.entity with
        | Some entity when entity.entity = Domain.entity.Cogmind -> true
        | _ -> false)

let mobs tiles =
    tiles
    |> List.find (fun tile ->
        match tile.entity with
        | Some entity when entity.entity <> Domain.entity.Cogmind -> true
        | _ -> false)
