module Model

open Magic
open Domain

type Propulsion =
    | Flight
    | Hover
    | Wheel
    | Legs
    | Treads

type Utility =
    | Device
    | Processor
    | Armor
    | Storage

type Weapon =
    | Launcher
    | Gun
    | Cannon
    | Special
    | Melee

type ItemCategory =
    | Power
    | Propulsion of Propulsion
    | Utility of Utility
    | Weapon of Weapon
    | Misc

let itemToCategory (item: item) : ItemCategory =
    match item with
    | item.Matter
    | item.DataCore
    | item.DerelictLog
    | item.SchematicArchive
    | item.ImprinterDataCore
    | item.A2DataCore
    | item.A7DataCore
    | item.MaincDataCore
    | item.ArchitectDataCore
    | item.Scrap
    | item.Protomatter -> Misc
    | item.IonEngine
    | item.LgtIonEngine
    | item.BackupPowerI
    | item.ImpIonEngine
    | item.RnfIonEngine
    | item.HvyIonEngine
    | item.CldIonEngine
    | item.DeuteriumEngine
    | item.LgtDeuteriumEngine
    | item.BackupPowerIii
    | item.NuclearCore
    | item.LgtNuclearCore
    | item.ImpDeuteriumEngine
    | item.RnfDeuteriumEngine
    | item.HybDeuteriumEngine
    | item.HvyDeuteriumEngine
    | item.CldDeuteriumEngine
    | item.EnhNuclearCore
    | item.MicNuclearCore
    | item.MakPowerSource
    | item.AngularMomentumEngine
    | item.LgtAngularMomentumEngine
    | item.FcellEngine
    | item.FissionCore
    | item.LgtFissionCore
    | item.HybFissionCore
    | item.FusionCompressor
    | item.ColdFusionReactor
    | item.NeutrinoCore
    | item.LgtNeutrinoCore
    | item.RnfFissionCore
    | item.EnhFissionCore
    | item.CldFissionCore
    | item.MicFissionCore
    | item.FusionReactor
    | item.AntimatterReactor
    | item.LgtAntimatterReactor
    | item.RnfAntimatterReactor
    | item.HybAntimatterReactor
    | item.BackupPowerVii
    | item.HvyAntimatterReactor
    | item.MniFusionReactor
    | item.ImpFusionCompressor
    | item.MicNeutrinoCore
    | item.ZioLightDmReactor
    | item.ZioHeavyDmReactor
    | item.ParticleReactor
    | item.LgtParticleReactor
    | item.MicAntimatterReactor
    | item.ComParticleReactor
    | item.CldAntimatterReactor
    | item.GravitonReactor
    | item.AsbFluxGenerator
    | item.QuantumReactor
    | item.LgtQuantumReactor
    | item.RnfQuantumReactor
    | item.ImpQuantumReactor
    | item.ZeropointReactor
    | item.VortexChainReactor
    | item.SingularityReactor -> Power
    | item.MatterDrive -> Utility Device
    | item.LgtTreads
    | item.ImpTreads
    | item.SpkTreads
    | item.ArmTreads
    | item.AdvTreads
    | item.MedTreads
    | item.ImpMediumTreads
    | item.SpkMediumTreads
    | item.ArmMediumTreads
    | item.HvyTreads
    | item.AdvMediumTreads
    | item.EnhArmoredMediumTreads
    | item.ImpHeavyTreads
    | item.HvySiegeTreads
    | item.SpkHeavyTreads
    | item.BiometalMediumTreads
    | item.ArmHeavyTreads
    | item.AdvHeavyTreads
    | item.ImpHeavySiegeTreads
    | item.CentriumHeavyTreads
    | item.Megatreads
    | item.BiometalHeavyTreads
    | item.ExpBiometalHeavyTreads
    | item.EnhArmoredHeavyTreads
    | item.AdvHeavySiegeTreads
    | item.HdnCentriumHeavyTreads
    | item.ExpBiometalMediumTreads -> Propulsion Treads
    | item.AluminumLeg
    | item.ImpAluminumLeg
    | item.CarbonfiberLeg
    | item.TitaniumLeg
    | item.VssLeg
    | item.ImpCarbonfiberLeg
    | item.ImpTitaniumLeg
    | item.MakLeg
    | item.FlexicarbonLeg
    | item.ArmLeg
    | item.ImpVssLeg
    | item.ZioCompositeLegI
    | item.EnhFlexicarbonLeg
    | item.EnhArmoredLeg
    | item.MyomerLeg
    | item.AdvVssLeg
    | item.AdvMyomerLeg
    | item.ExpFlexicarbonLeg
    | item.ZioCompositeLegIi
    | item.EtherialTendrils
    | item.BiometalLeg
    | item.EnhBiometalLeg
    | item.ExpMyomerLeg
    | item.TrollExoskeleton
    | item.AsbAlloyLeg
    | item.CentriumLeg
    | item.HdnCentriumLeg
    | item.ExpBiometalLeg
    | item.SigixExoskeleton
    | item.ZioSupercompositeLeg
    | item.PotentialLeg
    | item.MyomerExoskeleton -> Propulsion Legs
    | item.Wheel
    | item.ComWheel
    | item.ArmWheel
    | item.ArmHugeWheel
    | item.CentriumWheel
    | item.HdnCentriumWheel -> Propulsion Wheel
    | item.HoverUnit
    | item.BackupPropulsionI
    | item.ImpHoverUnit
    | item.Airjet
    | item.AerolevUnit
    | item.AsbHoverUnit
    | item.BackupPropulsionIii
    | item.GravmagSystem
    | item.AsbHoverSystem
    | item.ImpAirjet
    | item.CldAirjet
    | item.ImpGravmagSystem
    | item.CldAerolevUnit
    | item.CmbAirjet
    | item.GravmagArray
    | item.MakHoverUnit
    | item.ZioGlidesysI
    | item.AntigravSystem
    | item.GyrokineticInverter
    | item.LinearGravjet
    | item.CldGravmagSystem
    | item.CmbGravmagSystem
    | item.ImpAntigravSystem
    | item.ImpGyrokineticInverter
    | item.ImpLinearGravjet
    | item.BackupPropulsionVii
    | item.ZioGlidesysIi
    | item.CldAntigravSystem
    | item.CmbAntigravSystem
    | item.AntigravArray
    | item.ExpGyrokineticInverter
    | item.CldLinearGravjet
    | item.CmbLinearGravjet -> Propulsion Hover
    | item.FlightUnit
    | item.VtolModule
    | item.ImpFlightUnit
    | item.CesiumionThruster
    | item.SurgeThruster
    | item.ImpVtolModule
    | item.XenonBombardmentThruster
    | item.ImpCesiumionThruster
    | item.CldVtolModule
    | item.MakFlightUnit
    | item.NuclearPulseThruster
    | item.ImpSurgeThruster
    | item.MniNuclearPulseThruster
    | item.CldCesiumionThruster
    | item.BiomechanicalWings
    | item.FieldPropulsionDrive
    | item.CldNuclearPulseThruster
    | item.ExpCesiumionThruster
    | item.NuclearPulseArray
    | item.MakMicrothruster
    | item.ImpulseThruster
    | item.AdvSurgeThruster
    | item.CldFieldPropulsionDrive
    | item.FieldPropulsionArray
    | item.DiametricDrive
    | item.FlyingFortressV7
    | item.Tthruster
    | item.IntegratedTrackerDrive
    | item.EtherialPropulsion
    | item.Qthruster
    | item.ElectronDiverter
    | item.ImpDiametricDrive
    | item.CldImpulseThruster
    | item.ImpulseThrusterArray
    | item.ImpQthruster
    | item.CldQthruster
    | item.ExpQthruster -> Propulsion Flight
    | item.Desublimator
    | item.PowerAmplifier
    | item.AdvPowerAmplifier
    | item.ExpPowerAmplifier
    | item.ThermalGenerator
    | item.ImpThermalGenerator
    | item.AdvThermalGenerator
    | item.ExpThermalGenerator
    | item.CryofiberWeb
    | item.ImpCryofiberWeb
    | item.AdvCryofiberWeb
    | item.HeatSink
    | item.ImpHeatSink
    | item.AdvHeatSink
    | item.ExpHeatSink
    | item.CoolingSystem
    | item.ImpCoolingSystem
    | item.AdvCoolingSystem
    | item.ExpCoolingSystem
    | item.CoolantNetwork
    | item.AsbNanovents
    | item.FrostArray
    | item.DisposableHeatSink
    | item.CoolantInjector
    | item.ImpCoolantInjector
    | item.AdvCoolantInjector
    | item.ExpCoolantInjector -> Utility Device
    | item.SmlStorageUnit
    | item.MedStorageUnit
    | item.LrgStorageUnit
    | item.HcpStorageUnit
    | item.HugeStorageUnit
    | item.CargoStorageUnit
    | item.Humpback
    | item.Lightpack20
    | item.SmlBattery
    | item.MedBattery
    | item.LrgBattery
    | item.HcpBattery
    | item.ComBattery
    | item.EnergyWell
    | item.ImpEnergyWell
    | item.AdvEnergyWell
    | item.ExpEnergyWell
    | item.ZioBiocell
    | item.AsbBiocellArray
    | item.ZioBiocellArray
    | item.Superbattery
    | item.SmlMatterPod
    | item.MedMatterPod
    | item.LrgMatterPod
    | item.HcpMatterPod
    | item.ComMatterPod
    | item.MatterCompressor
    | item.ImpMatterCompressor
    | item.AdvMatterCompressor
    | item.ExpMatterCompressor
    | item.Yiuf0sBottomlessMatterPit -> Utility Storage
    | item.WeightRedistSystem
    | item.AdvWeightRedistSystem
    | item.GravityNeutralizer
    | item.AdvGravityNeutralizer
    | item.QuantumShadingMachine
    | item.AsbSuspensionFrame
    | item.AdvQuantumShadingMachine
    | item.AsbMetafiberNetwork
    | item.ZioMetafieldGenerator
    | item.StFieldCompressor
    | item.StructuralScanner
    | item.TrapScanner
    | item.ImpTrapScanner
    | item.MakTrapScanner
    | item.AdvTrapScanner
    | item.MachineAnalyzer
    | item.Triangulator
    | item.VisualProcessingUnit
    | item.AdvVisualProcessingUnit
    | item.EnhOpticalArray
    | item.ExpOpticalArray
    | item.SpectralAnalyzer
    | item.SensorArray
    | item.ImpSensorArray
    | item.AdvSensorArray
    | item.LrnSensorArray
    | item.MakSensorArray
    | item.ExpSensorArray -> Utility Device
    | item.SignalInterpreter
    | item.ImpSignalInterpreter
    | item.AdvSignalInterpreter
    | item.ExpSignalInterpreter
    | item.ActiveSensorSuite -> Utility Processor
    | item.TerrainScanner
    | item.ImpTerrainScanner
    | item.AdvTerrainScanner
    | item.MakTerrainScanner
    | item.LrnTerrainScanner
    | item.ExpTerrainScanner
    | item.Surveybot24Scanner -> Utility Device
    | item.TerrainScanProcessor
    | item.ImpTerrainScanProcessor
    | item.MakTerrainScanProcessor
    | item.AdvTerrainScanProcessor
    | item.ExpTerrainScanProcessor
    | item.Surveybot24Chip -> Utility Processor
    | item.SeismicDetector -> Utility Device
    | item.TransportNetworkCoupler
    | item.ModifiedTnc
    | item.b10DecoderChipgeneric
    | item.b10DecoderChiplooter
    | item.b10DecoderChipscout
    | item.b10DecoderChipskirmisher
    | item.b10AlertChip
    | item.SalvageTargetingComputer
    | item.ImpSalvageTargetingComputer
    | item.MakSalvageTargetingComputer
    | item.AdvSalvageTargetingComputer
    | item.AsbCombatSuite
    | item.TargetingComputer
    | item.ImpTargetingComputer
    | item.AdvTargetingComputer
    | item.ExpTargetingComputer
    | item.TacticalCoordinationSuite
    | item.MeleeAnalysisSuite
    | item.ImpMeleeAnalysisSuite
    | item.AdvMeleeAnalysisSuite
    | item.ExpMeleeAnalysisSuite
    | item.LauncherGuidanceComputer
    | item.ImpLauncherGuidanceComputer
    | item.AdvLauncherGuidanceComputer
    | item.TargetAnalyzer
    | item.ImpTargetAnalyzer
    | item.AdvTargetAnalyzer
    | item.ExpTargetAnalyzer
    | item.CoreAnalyzer
    | item.ExpCoreAnalyzer
    | item.ArmorIntegrityAnalyzer
    | item.ImpArmorIntegrityAnalyzer
    | item.ExpArmorIntegrityAnalyzer -> Utility Processor
    | item.RecoilStabilizer
    | item.RecoilNullifier
    | item.MatterFilter
    | item.PrcMatterFilter
    | item.EnergyFilter
    | item.PrcEnergyFilter
    | item.ParticleCharger
    | item.ImpParticleCharger
    | item.AdvParticleCharger
    | item.ParticleAccelerator
    | item.ImpParticleAccelerator
    | item.AdvParticleAccelerator
    | item.Kinecellerator
    | item.ImpKinecellerator
    | item.AdvKinecellerator
    | item.LauncherLoader
    | item.QuantumCapacitor
    | item.WeaponCycler
    | item.ImpWeaponCycler
    | item.AdvWeaponCycler
    | item.ExpWeaponCycler
    | item.Microactuators
    | item.Nanoactuators
    | item.Femtoactuators
    | item.ActuatorArray
    | item.ImpActuatorArray
    | item.AdvActuatorArray
    | item.ExpActuatorArray
    | item.ForceBooster
    | item.ImpForceBooster
    | item.AdvForceBooster
    | item.StasisCanceller
    | item.TransmissionJammer
    | item.MakTransmissionJammer
    | item.ImpTransmissionJammer
    | item.AdvTransmissionJammer
    | item.ExpTransmissionJammer
    | item.EcmSuite
    | item.MakEcmSuite
    | item.AdvEcmSuite
    | item.ExpEcmSuite
    | item.ReactionControlSystem
    | item.ImpReactionControlSystem
    | item.AdvReactionControlSystem
    | item.ExpReactionControlSystem
    | item.PhaseShifter
    | item.ImpPhaseShifter
    | item.AdvPhaseShifter
    | item.ExpPhaseShifter
    | item.CloakingDevice
    | item.MakCloakingDevice
    | item.ImpCloakingDevice
    | item.AdvCloakingDevice
    | item.ExpCloakingDevice
    | item.CloakOfProtection
    | item.had0sCloak -> Utility Device
    | item.CoreShielding
    | item.ImpCoreShielding
    | item.ExpCoreShielding
    | item.PowerShielding
    | item.ImpPowerShielding
    | item.ExpPowerShielding
    | item.PropulsionShielding
    | item.ImpPropulsionShielding
    | item.ExpPropulsionShielding
    | item.UtilityShielding
    | item.ImpUtilityShielding
    | item.ExpUtilityShielding
    | item.WeaponShielding
    | item.ImpWeaponShielding
    | item.ExpWeaponShielding
    | item.ZioWeaponCasing
    | item.LgtArmorPlating
    | item.MedArmorPlating
    | item.HvyArmorPlating
    | item.ZioLightCarapace
    | item.ZioHeavyCarapace
    | item.HrdLightArmorPlating
    | item.HrdMediumArmorPlating
    | item.HrdHeavyArmorPlating
    | item.ImpLightArmorPlating
    | item.ImpMediumArmorPlating
    | item.ImpHeavyArmorPlating
    | item.LyrLightArmorPlating
    | item.MakArmorPlating
    | item.LyrMediumArmorPlating
    | item.LyrHeavyArmorPlating
    | item.CentriumLightArmorPlating
    | item.CentriumMediumArmorPlating
    | item.CentriumHeavyArmorPlating
    | item.CentriumLinkedPlating
    | item.ReactivePlating
    | item.MedReactivePlating
    | item.MakKineticPlating
    | item.HvyReactivePlating
    | item.ReflectivePlating
    | item.MedReflectivePlating
    | item.MakThermalPlating
    | item.HvyReflectivePlating
    | item.rawnsArmorth
    | item.rawnsArmorex
    | item.InsulatedPlating
    | item.MedInsulatedPlating
    | item.HvyInsulatedPlating
    | item.DamperPlating
    | item.ZioShadeCarapace
    | item.ZioShadeArmor
    | item.AsbAlloyArmor
    | item.MakAblativeArmor
    | item.ActiveCoolingArmor
    | item.PoweredArmor
    | item.ImpPoweredArmor
    | item.AdvPoweredArmor
    | item.ExpPoweredArmor
    | item.cutusBuckler
    | item.LgtRegenerativePlating
    | item.MedRegenerativePlating
    | item.HvyRegenerativePlating
    | item.ShellArmor
    | item.PhaseArmor
    | item.GrapheneBrace
    | item.FocalShield
    | item.ImpFocalShield
    | item.AdvFocalShield
    | item.ExpFocalShield
    | item.ThermalShield
    | item.ImpThermalShield
    | item.AdvThermalShield
    | item.ExpThermalShield
    | item.ThermalBarrier
    | item.BeamSplitter
    | item.ThermalDefenseSuite
    | item.ImpThermalDefenseSuite
    | item.AdvThermalDefenseSuite
    | item.ExpThermalDefenseSuite
    | item.ShockAbsorptionSystem
    | item.ImpShockAbsorptionSystem
    | item.ExpShockAbsorptionSystem
    | item.EmDisruptionField
    | item.AdvEmDisruptionField
    | item.ExpEmDisruptionField
    | item.MerlnsChromaticScreen
    | item.HardlightGenerator
    | item.ImpHardlightGenerator
    | item.AdvHardlightGenerator
    | item.ExpHardlightGenerator
    | item.ShieldGenerator
    | item.ImpShieldGenerator
    | item.AdvShieldGenerator
    | item.ExpShieldGenerator
    | item.ForceField
    | item.ImpForceField
    | item.AdvForceField
    | item.ExpForceField
    | item.vrtlsUltimateField
    | item.VortexFieldProjector
    | item.RemoteShield
    | item.ImpRemoteShield
    | item.AdvRemoteShield
    | item.RemoteForceField
    | item.ImpRemoteForceField
    | item.EnergyMantle
    | item.ImpEnergyMantle
    | item.AegisRemoteShield
    | item.PhaseRedirector
    | item.PointDefenseSystem
    | item.PointDefenseArray
    | item.AntimissileSystem -> Utility Armor
    | item.ExChip1
    | item.HackingSuite
    | item.MakHackingSuite
    | item.ImpHackingSuite
    | item.AdvHackingSuite
    | item.ExpHackingSuite
    | item.SystemMapper
    | item.DeepNetworkScanner
    | item.ArchitectGodChipA
    | item.ExChip2
    | item.SystemShield
    | item.MakSystemShield
    | item.ImpSystemShield
    | item.AdvSystemShield
    | item.ExpSystemShield
    | item.GhostBarrier
    | item.QuantumRouter
    | item.ArchitectGodChipD
    | item.Authchiprnc
    | item.Authchiprcombat
    | item.Authchippower
    | item.Authchippropulsion
    | item.Authchipdevice
    | item.Authchipstorage
    | item.Authchipprocessor
    | item.Authchiparmor
    | item.Authchipweapon
    | item.RelayCouplernc
    | item.RelayCouplerc
    | item.RelayCouplerarc
    | item.RelayCouplerswarmer
    | item.RelayCouplercutter
    | item.RelayCouplergrunt
    | item.RelayCouplerbrawler
    | item.RelayCouplerduelist
    | item.RelayCouplersentry
    | item.RelayCouplerdemolisher
    | item.RelayCouplerspecialist
    | item.RelayCouplerhunter
    | item.RelayCouplerheavy
    | item.RelayCouplerbehemoth
    | item.RelayCouplerprogrammer -> Utility Processor
    | item.SkeletonBox
    | item.mtfsAutohacker
    | item.ComponentAnalysisSuite
    | item.ImpComponentAnalysisSuite
    | item.AdvComponentAnalysisSuite
    | item.DynamicInsulationSystem
    | item.ImpDynamicInsulationSystem
    | item.AdvDynamicInsulationSystem
    | item.SystemGuard
    | item.ImpSystemGuard
    | item.ExpSystemGuard
    | item.CorruptionScreen
    | item.ImpCorruptionScreen
    | item.AdvCorruptionScreen
    | item.SystemRestorationModule
    | item.MakSystemRestorationModule
    | item.ImpSystemRestorationModule
    | item.AdvSystemRestorationModule
    | item.SystemPurifier
    | item.ExpSystemPurifier
    | item.TractorBeam
    | item.HpwTractorBeam
    | item.LrnTractorBeam
    | item.MobileRefineryMkCclxvii
    | item.TrapExtractor
    | item.ImpTrapExtractor
    | item.AdvTrapExtractor
    | item.TrapReconfigurator
    | item.Recalibrator
    | item.ImpRecalibrator
    | item.AdvRecalibrator
    | item.FieldRecyclingUnit
    | item.ImpFieldRecyclingUnit
    | item.AdvFieldRecyclingUnit
    | item.ExpFieldRecyclingUnit
    | item.DroneBay
    | item.ZdroneBay
    | item.MniDroneBay
    | item.MappingDroneBay
    | item.AdvDroneBay
    | item.BombDroneBay
    | item.ThiefDroneBay
    | item.DecoyDroneBay
    | item.SpliceDroneBay
    | item.CombatDroneBay
    | item.AssaultDroneBay
    | item.StealthDroneBay
    | item.SwarmDroneBay
    | item.SupersonicDroneBay
    | item.SensorDroneBay
    | item.HackingDroneBay
    | item.MinesnifferDroneBay
    | item.Armyinabox
    | item.WardroneBay
    | item.BombFactoryNo2
    | item.MobileAssemblyUnit
    | item.HeartOfSteel
    | item.GolemUnit
    | item.PsuRigger
    | item.PhasingAfg
    | item.AsneutralizerNo17b
    | item.Chronowheel
    | item.DimensionalNodeInitializer
    | item.TransdimensionalReconstructor
    | item.HpwTransdimensionalReconstructor
    | item.CoreExpander
    | item.CoreRegenerator
    | item.IntegrityRedistributor
    | item.IntegratedDissipator
    | item.SuperchargedIntegratedDissipator
    | item.IntegratedThermoelectricNetwork
    | item.IntegratedReactor
    | item.SuperchargedIntegratedReactor
    | item.IntegratedMediator
    | item.CoreMembrane
    | item.NavigationEfficiencyMatrix
    | item.CoreResetMatrix
    | item.SubatomicReplicator
    | item.Terrabomb
    | item.CorePhysicsCalibrator
    | item.SpacefoldActivator
    | item.MicrowarpDrive
    | item.LcCapacitor
    | item.LrcArmor
    | item.LrcStorage
    | item.LrcEnergyWell
    | item.LrcMatterCompressor
    | item.LrcBoosters
    | item.LrcInsulator -> Utility Device
    | item.EmPulseGun
    | item.HvyEmPulseGun
    | item.EmShotgun
    | item.ImpEmShotgun
    | item.ShockRifle
    | item.RiotGun
    | item.HvyEmShotgun
    | item.LightningGun
    | item.HvyRiotGun
    | item.ArcProjector
    | item.PrcShockRifle
    | item.HpwShockRifle
    | item.ArcThrower
    | item.ImpLightningGun
    | item.TeslaRifle
    | item.ImpArcProjector
    | item.HvyTeslaRifle
    | item.HypEmGaussRifle
    | item.ImpArcThrower
    | item.mtfsShockpuncher
    | item.GammaRifle
    | item.TachyonDispersionRay
    | item.Immobilizer
    | item.ModifiedEmGaussRifle
    | item.Awsexdec
    | item.EnhGammaRifle
    | item.MedLaser
    | item.SmlLaser
    | item.BackupLaserI
    | item.BeamRifle
    | item.ParticleGun
    | item.SpreadLaser
    | item.ImpMediumLaser
    | item.FieldLaser
    | item.PulseRifle
    | item.BackupLaserIii
    | item.HvyParticleGun
    | item.PrcBeamRifle
    | item.AdvBeamRifle
    | item.HvyLaser
    | item.GatlingLaser
    | item.CldPulseRifle
    | item.HpwFieldLaser
    | item.ImpSpreadLaser
    | item.MakLaser
    | item.PlasmaRifle
    | item.ThermicLaser
    | item.Beamcaster
    | item.ForceRifle
    | item.ImpHeavyLaser
    | item.StormLaser
    | item.ZioLasers
    | item.WaveGun
    | item.VariableChargeGun
    | item.HvyBeamcaster
    | item.CldPlasmaRifle
    | item.EnhForceRifle
    | item.HvyGatlingLaser
    | item.ZioPhasers
    | item.PhaseGun
    | item.DispersionRifle
    | item.BackupLaserVii
    | item.PlasmaStorm
    | item.AdvPlasmaRifle
    | item.HvyWaveGun
    | item.AdvVariableChargeGun
    | item.CldPhaseGun
    | item.LrnGatlingLaser
    | item.WarpGun
    | item.VortexRifle
    | item.ZioLaserm
    | item.Awsthermal
    | item.PdLaser
    | item.QuantumRifle
    | item.PrcPhaseGun
    | item.HvyDispersionRifle
    | item.VortexShotgun
    | item.VortexRail
    | item.ZioPhaserm
    | item.EnhQuantumRifle
    | item.ZioLaserh
    | item.HvyQuantumRifle
    | item.ZioPhaserh
    | item.GatlingBeam
    | item.SigixSheargun
    | item.ModifiedSigixSheargun -> Weapon Gun
    | item.LgtEmPulseCannon
    | item.EmPulseCannon
    | item.ImpEmPulseCannon
    | item.ProtonCannon
    | item.LrnProtonCannon
    | item.DisruptorCannon
    | item.HvyProtonCannon
    | item.HerfCannon
    | item.HvyDisruptorCannon
    | item.CldProtonCannon
    | item.ProtonBurstCannon
    | item.ComHerfCannon
    | item.LatentEnergyStreamer
    | item.Nk0lasTeslaDoomcannon
    | item.Emds
    | item.HpwDisruptorCannon
    | item.BeamCannon
    | item.ParticleCannon
    | item.AdvBeamCannon
    | item.HvyParticleCannon
    | item.IonCannon
    | item.PlasmaCannon
    | item.HvyIonCannon
    | item.CldParticleCannon
    | item.PhaseCannon
    | item.HvyPlasmaCannon
    | item.CldPlasmaCannon
    | item.ComIonCannon
    | item.IonBurstCannon
    | item.AdvPlasmaCannon
    | item.HvyPhaseCannon
    | item.NeutronCannon
    | item.MatterNeutralizer
    | item.HvyNeutronCannon
    | item.LrnPhaseCannon
    | item.CldPhaseCannon
    | item.VortexCannon
    | item.GuiPlasmaCannon
    | item.NovaCannon
    | item.ImpMatterNeutralizer
    | item.VortexDriver
    | item.ZioAlphaCannon
    | item.AsbFocalCannon
    | item.EnhNovaCannon
    | item.Firepult
    | item.YoloCannon
    | item.PotentialCannon
    | item.WarpCannon
    | item.CldNovaCannon
    | item.NullCannon
    | item.ImpPotentialCannon
    | item.Disintegrator
    | item.CoreCannon
    | item.SigixShearcannon
    | item.DrainedLcannon
    | item.Lcannon
    | item.ZioAlphaCannonMkIi
    | item.Bfg9kVortexEdition -> Weapon Cannon
    | item.AssaultRifle
    | item.AsbRifle
    | item.LgtAssaultRifle
    | item.HvyAssaultRifle
    | item.Autogun
    | item.Shotgun
    | item.BattleRifle
    | item.AsbHeavyRifle
    | item.ImpAssaultRifle
    | item.Minigun
    | item.HpwShotgun
    | item.AsbShotgun
    | item.BarrageGun
    | item.EnhAutogun
    | item.GaussRifle
    | item.AsbGaussRifle
    | item.FlakGun
    | item.PrcAssaultRifle
    | item.HvyBattleRifle
    | item.MakShrapnelGun
    | item.CoilGun
    | item.HypGaussRifle
    | item.HvyMachineGun
    | item.ImpHeavyMachineGun
    | item.ComGaussRifle
    | item.XlAutogunSubcomponent
    | item.KePenetrator
    | item.HypCoilGun
    | item.ImpKePenetrator
    | item.EnhCoilGun
    | item.ComCoilGun
    | item.Railgun
    | item.AdvKePenetrator
    | item.LinkedAutogun
    | item.Awsgauss
    | item.HypRailgun
    | item.HelicalRailgun
    | item.ComRailgun
    | item.XlAutogunArray
    | item.ashsBoomstick
    | item.rawnsBoregun
    | item.Multirail
    | item.HypMultirail
    | item.had0sSniperRifle
    | item.A3sSniperRifle -> Weapon Gun
    | item.LgtCannon
    | item.ImpLightCannon
    | item.BattleCannon
    | item.AssaultCannon
    | item.HvyAssaultCannon
    | item.FlakCannon
    | item.AdvAssaultCannon
    | item.GaussCannon
    | item.SlugCannon
    | item.MniAssaultCannon
    | item.MagneticAccelerationCannon
    | item.HvyFlakCannon
    | item.BoreCannon
    | item.AntimatterCannon
    | item.MassDriver
    | item.HvyMassDriver
    | item.EnhGaussCannon
    | item.HypGaussCannon
    | item.TrirailAccelerator
    | item.HardcellCannon
    | item.HvyGaussCannon
    | item.HypMassDriver
    | item.HvyAutocannon
    | item.DasCannon
    | item.LgtAntimatterCannon
    | item.LinearAccelerator
    | item.HvyLinearAccelerator
    | item.ComMassDriver
    | item.HvyHardcellCannon
    | item.ComLinearAccelerator
    | item.HypLinearAccelerator
    | item.HclLinearAccelerator
    | item.GravitonCannon
    | item.BlastCannon
    | item.P13cesGatlingFlakker
    | item.Awsautocannon
    | item.Perforator
    | item.OmegaCannon -> Weapon Cannon
    | item.EmpBlaster
    | item.ShockBombLauncher
    | item.AdvEmpBlaster
    | item.ProtonMissileLauncher
    | item.ImpProtonMissileLauncher
    | item.GuiEmpBlaster
    | item.HvyShockBombLauncher
    | item.TeslaBombLauncher
    | item.HvyProtonMissileLauncher
    | item.ComTeslaBombLauncher
    | item.GammaBombArray
    | item.EnhGammaBombArray
    | item.GrenadeLauncher
    | item.RocketLauncher
    | item.MniGrenadeLauncher
    | item.ImpGrenadeLauncher
    | item.MissileLauncher
    | item.ConcussiveRpg
    | item.Yiuf0sDoublenader
    | item.HvyRocketLauncher
    | item.HvyMissileLauncher
    | item.GuiMissileLauncher
    | item.PrcGrenadeLauncher
    | item.RocketArray
    | item.LrnMissileLauncher
    | item.ImpConcussiveRpg
    | item.PrcRocketLauncher
    | item.ScatterRocketArray
    | item.SmartbombLauncher
    | item.MniSmartbombLauncher
    | item.TiamatMissileLauncher
    | item.Thermoblaster
    | item.MicronukeLauncher
    | item.AdvConcussiveRpg
    | item.NeutronMissileLauncher
    | item.FusionBombLauncher
    | item.HellfireMissileLauncher
    | item.AdvMicronukeLauncher
    | item.TacticalQuantumWarhead
    | item.VortexCatalystActivator
    | item.ChainMissileLauncher
    | item.RagnarokMissileLauncher
    | item.PointSingularityLauncher
    | item.GuiMicronukeLauncher
    | item.tntsNukerbomber
    | item.ZbombDeliverySystem
    | item.SigixTerminator
    | item.SuperchargedSigixTerminator
    | item.ContainmentFacilitator
    | item.Detonator -> Weapon Launcher
    | item.DirtyDatajack
    | item.SpliceInjector
    | item.Datajack
    | item.ImpDatajack
    | item.AdvDatajack
    | item.RemoteDatajack
    | item.ImpRemoteDatajack
    | item.AdvRemoteDatajack
    | item.ExpRemoteDatajack
    | item.GuiRemoteDatajack
    | item.MerlnsWand
    | item.FieldLobotomyKit
    | item.MiningLaser
    | item.WeldingTorch
    | item.PlasmaCutter
    | item.ImpPlasmaCutter
    | item.Flamer
    | item.AsbFtorch
    | item.EnhFlamer
    | item.PlasmaFlamer
    | item.AsbPtorch
    | item.Run14sThrowingClaymores
    | item.Run14sThrowingClaymoresV3
    | item.Ad0rfsMagmablaster
    | item.StasisBeam
    | item.StasisProjector
    | item.ExpStasisProjector
    | item.MolecularDeconstructor -> Weapon Special
    | item.Hammer
    | item.Mace
    | item.Flail
    | item.Maul
    | item.AsbMaul
    | item.HvyHammer
    | item.HvyMace
    | item.HvyFlail
    | item.GreatMaul
    | item.PoweredHammer
    | item.MakHammer
    | item.PowerMaul
    | item.AsbPmaul
    | item.ImpactMace
    | item.ShockMaul
    | item.ThunderHammer
    | item.Compactor
    | item.GravityFlail
    | item.ClanksMallet
    | item.CoreStripper
    | item.MiningClaw
    | item.Ec_1
    | item.Katana
    | item.AsbBlade
    | item.Scythe
    | item.Axe
    | item.BladeSaw
    | item.Ec_3
    | item.Chainsword
    | item.Ripper
    | item.MakAxe
    | item.MakSword
    | item.GreatAxe
    | item.Greatsword
    | item.PowerSword
    | item.AsbPsword
    | item.Falx
    | item.CarbideSaw
    | item.Segregator
    | item.Tearclaws
    | item.Ec_5
    | item.PhasingSabre
    | item.PlasmaSword
    | item.IonicAxe
    | item.MniTearclaws
    | item.DualbladeSaw
    | item.Vibroblade
    | item.MolecularScythe
    | item.CentriumGreatsword
    | item.MasterTearclaws
    | item.Longsword1
    | item.Ec_7
    | item.Nanosword
    | item.ParticleCleaver
    | item.CentriumClaws
    | item.cutusSwordlootmaker
    | item.cutusSwordchoppy
    | item.VortexShredder
    | item.Ec_9
    | item.SigixBroadsword
    | item.Spear
    | item.MakSpear
    | item.Cra16sPointyStick
    | item.HvyPick
    | item.Lance
    | item.KineticSpear
    | item.ForceLance
    | item.PlasmaLance
    | item.EnhForceLance
    | item.VortexLance
    | item.Cra16sBehemothSlayer -> Weapon Melee
    | item.BladeTrap
    | item.SegregatorTrap
    | item.ExplosiveTrap
    | item.HeavyExplosiveTrap
    | item.TiamatBombTrap
    | item.FusionBombTrap
    | item.HellfireTrap
    | item.ArmageddonTrap
    | item.DirtyBombTrap
    | item.EmpTrap
    | item.ProtonBombTrap
    | item.TeslaBombTrap
    | item.GammaBombTrap
    | item.ShockTrap
    | item.EmSurgeTrap
    | item.FireTrap
    | item.StasisTrap
    | item.SignalGenerator
    | item.SelfdestructInterrupter
    | item.SapperCharge
    | item.Deployasentry
    | item.GalModule
    | item.PortableAfg
    | item.SgempPrototype
    | item.TerrabombDerivative
    | item.SigixContainmentPod
    | item.SigixCorpse
    | item.Meganuke
    | item.GammaRefractor -> Misc
    | _ -> Misc

let itemToChar (item: item) : string =
    match itemToCategory item with
    | Propulsion _ -> "="
    | Power -> "*"
    | Misc -> "~"
    | Utility _ -> "!"
    | Weapon weapon ->
        match weapon with
        | Cannon -> "]"
        | Launcher -> "]"
        | Gun -> "["
        | Melee -> "/"
        | Special -> "~"

let cellToChar (tile: LuigiTile) : string =
    match tile.cell with
    | cell.SEALED_DOOR
    | cell.DOOR_SAN
    | cell.DOOR_SCR
    | cell.DOOR_MAT
    | cell.DOOR_FAC
    | cell.DOOR_RES
    | cell.DOOR_ACC
    | cell.DOOR_SUR
    | cell.DOOR_MIN
    | cell.DOOR_EXI
    | cell.DOOR_STO
    | cell.DOOR_REC
    | cell.DOOR_WAS
    | cell.DOOR_GAR
    | cell.DOOR_DSF
    | cell.DOOR_LOW
    | cell.DOOR_UPP
    | cell.DOOR_PRO
    | cell.DOOR_DEE
    | cell.DOOR_ZIO
    | cell.DOOR_DAT
    | cell.DOOR_ZHI
    | cell.DOOR_WAR
    | cell.DOOR_EXT
    | cell.DOOR_CET
    | cell.DOOR_ARC
    | cell.DOOR_HUB
    | cell.DOOR_ARM
    | cell.DOOR_LAB
    | cell.DOOR_QUA
    | cell.DOOR_TES
    | cell.DOOR_SEC
    | cell.DOOR_COM
    | cell.DOOR_AC0
    | cell.DOOR_LAI
    | cell.DOOR_TOW -> Some "+"
    | cell.TEMP_WALL
    | cell.WALL_SAN
    | cell.WALL_SCR
    | cell.WALL_MAT
    | cell.WALL_FAC
    | cell.WALL_RES
    | cell.WALL_ACC
    | cell.WALL_SUR
    | cell.WALL_MIN
    | cell.WALL_EXI
    | cell.WALL_STO
    | cell.WALL_REC
    | cell.WALL_WAS
    | cell.WALL_GAR
    | cell.WALL_DSF
    | cell.WALL_LOW
    | cell.WALL_UPP
    | cell.WALL_PRO
    | cell.WALL_DEE
    | cell.WALL_ZIO
    | cell.WALL_DAT
    | cell.WALL_ZHI
    | cell.WALL_WAR
    | cell.WALL_EXT
    | cell.WALL_CET
    | cell.WALL_ARC
    | cell.WALL_HUB
    | cell.WALL_ARM
    | cell.WALL_LAB
    | cell.WALL_QUA
    | cell.WALL_TES
    | cell.WALL_SEC
    | cell.WALL_COM
    | cell.WALL_AC0
    | cell.WALL_LAI
    | cell.WALL_TOW
    | cell.EARTH
    | cell.EARTH_EXC -> Some "#"
    | cell.FLOOR_SAN
    | cell.FLOOR_SCR
    | cell.FLOOR_MAT
    | cell.FLOOR_FAC
    | cell.FLOOR_RES
    | cell.FLOOR_ACC
    | cell.FLOOR_SUR
    | cell.FLOOR_MIN
    | cell.FLOOR_EXI
    | cell.FLOOR_STO
    | cell.FLOOR_REC
    | cell.FLOOR_WAS
    | cell.FLOOR_GAR
    | cell.FLOOR_DSF
    | cell.FLOOR_LOW
    | cell.FLOOR_UPP
    | cell.FLOOR_PRO
    | cell.FLOOR_DEE
    | cell.FLOOR_ZIO
    | cell.FLOOR_DAT
    | cell.FLOOR_ZHI
    | cell.FLOOR_WAR
    | cell.FLOOR_EXT
    | cell.FLOOR_CET
    | cell.FLOOR_ARC
    | cell.FLOOR_HUB
    | cell.FLOOR_ARM
    | cell.FLOOR_LAB
    | cell.FLOOR_QUA
    | cell.FLOOR_TES
    | cell.FLOOR_SEC
    | cell.FLOOR_COM
    | cell.FLOOR_AC0
    | cell.FLOOR_LAI
    | cell.FLOOR_TOW
    | cell.GROUND -> Some " "
    | cell.STAIRS_SAN
    | cell.STAIRS_SCR
    | cell.STAIRS_MAT
    | cell.STAIRS_FAC
    | cell.STAIRS_RES
    | cell.STAIRS_SUR
    | cell.STAIRS_ACC
    | cell.STAIRS_MIN
    | cell.STAIRS_EXI
    | cell.STAIRS_STO
    | cell.STAIRS_REC
    | cell.STAIRS_WAS
    | cell.STAIRS_GAR
    | cell.STAIRS_DSF
    | cell.STAIRS_LOW
    | cell.STAIRS_UPP
    | cell.STAIRS_PRO
    | cell.STAIRS_DEE
    | cell.STAIRS_ZIO
    | cell.STAIRS_DAT
    | cell.STAIRS_ZHI
    | cell.STAIRS_WAR
    | cell.STAIRS_EXT
    | cell.STAIRS_CET
    | cell.STAIRS_ARC
    | cell.STAIRS_HUB
    | cell.STAIRS_ARM
    | cell.STAIRS_LAB
    | cell.STAIRS_QUA
    | cell.STAIRS_TES
    | cell.STAIRS_SEC
    | cell.STAIRS_COM
    | cell.STAIRS_AC0
    | cell.STAIRS_LAI
    | cell.STAIRS_TOW
    | cell.STAIRS_NOACCESS
    | cell.STAIRS_BLOCKED
    | cell.STAIRS_GAR_OPEN
    | cell.STAIRS_DSF_OPEN
    | cell.STAIRS_SHORTCUT -> Some ">"
    | cell.SHORTCUT_SAN
    | cell.SHORTCUT_SCR
    | cell.SHORTCUT_MAT
    | cell.SHORTCUT_FAC
    | cell.SHORTCUT_RES
    | cell.SHORTCUT_ACC
    | cell.SHORTCUT_SUR
    | cell.SHORTCUT_MIN
    | cell.SHORTCUT_EXI
    | cell.SHORTCUT_STO
    | cell.SHORTCUT_REC
    | cell.SHORTCUT_WAS
    | cell.SHORTCUT_GAR
    | cell.SHORTCUT_DSF
    | cell.SHORTCUT_LOW
    | cell.SHORTCUT_UPP
    | cell.SHORTCUT_PRO
    | cell.SHORTCUT_DEE
    | cell.SHORTCUT_ZIO
    | cell.SHORTCUT_DAT
    | cell.SHORTCUT_ZHI
    | cell.SHORTCUT_WAR
    | cell.SHORTCUT_EXT
    | cell.SHORTCUT_CET
    | cell.SHORTCUT_ARC
    | cell.SHORTCUT_HUB
    | cell.SHORTCUT_ARM
    | cell.SHORTCUT_LAB
    | cell.SHORTCUT_QUA
    | cell.SHORTCUT_TES
    | cell.SHORTCUT_SEC
    | cell.SHORTCUT_COM
    | cell.SHORTCUT_AC0
    | cell.SHORTCUT_LAI
    | cell.SHORTCUT_TOW
    | cell.SHORTCUT_KNOWN -> Some "<"
    | _ -> None
    |> function
        | Some char ->
            match char with
            | " " ->
                match tile.item with
                | Some item -> itemToChar item.item
                | None ->
                    match tile.entity with
                    | Some entity when entity.entity = Domain.entity.Cogmind -> "@"
                    | Some _ -> "g"
                    | None -> " "
            | _ -> char
        | None -> "?"
